# Site Settings
title: "Darshan Fofadiya"
name: "Darshan Fofadiya"
description: "The Physics of Intelligence."
url: "https://darshanfofadiya.github.io"
baseurl: ""

# The Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # You can change to "air" or "contrast" later

# Author Info (Sidebar)
author:
  name: "Darshan Fofadiya"
  avatar: "/profile.jpg"
  bio: "Senior Applied Scientist @ Amazon.<br>Building System 2 for AI."
  location: "Seattle, WA"
  email: "fofadiyadarshan@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DarshanFofadiya"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=Tt2mt3EAAAAJ&hl=en" # Change this later
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/darshan-fofadiya"

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Navigation & UI Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
      classes: wide  # <--- THIS IS THE SECRET TO EUGENE YAN'S LOOK


